// pkg/gui/vue/src/panels/PanelPeers.vue
<script>
export default {
	name: 'Overview',
	data () { return { 
	duoSystem,
		pageSettings: { pageSize: 5 }
	}},
}
</script>

<template>	
<div class="rwrap">
	<ejs-grid :dataSource="this.duoSystem.peers" :allowPaging="true" :pageSettings='pageSettings'>
		<e-columns>
            <e-column field='addr' headerText='Address' textAlign='Right' width=90></e-column>
            <e-column field='pingtime' headerText='Ping time' width=120></e-column>
            <e-column field='bytessent' headerText='Sent' textAlign='Right' width=90></e-column>
			<e-column field='bytesrecv' headerText='Received' textAlign='Right' width=90></e-column>
			<e-column field='subver' headerText='Subversion' textAlign='Right' width=90></e-column>
			<e-column field='version' headerText='Version' textAlign='Right' width=90></e-column>
		</e-columns>
	</ejs-grid>
</div>
</template>

// pkg/gui/smelte/src/components/panels/PanelPeers.svelte
	Template: `<div class="rwrap">
        <ejs-grid :dataSource="this.duoSystem.peers" :allowPaging="true" :pageSettings='pageSettings'>
          <e-columns>
            <e-column field='addr' headerText='Address' textAlign='Right' width=90></e-column>
            <e-column field='pingtime' headerText='Ping time' width=120></e-column>
            <e-column field='bytessent' headerText='Sent' textAlign='Right' width=90></e-column>
			<e-column field='bytesrecv' headerText='Received' textAlign='Right' width=90></e-column>
			<e-column field='subver' headerText='Subversion' textAlign='Right' width=90></e-column>
			<e-column field='version' headerText='Version' textAlign='Right' width=90></e-column>
          </e-columns>
        </ejs-grid>
</div>`,
		Cs
