// pkg/gui/smelte/src/components/panels/PanelStatus.svelte
<script>
	export let status;
</script>

<div  id="panelstatus" class="Info">
	<ul class="rf flx flc noMargin noPadding justifyEvenly">
		<li class="flx fwd spb htg rr">
        			<span class="rcx2"></span>
        			<span class="rcx4">Version: </span>
        			<strong class="rcx6">{status.ver}</strong>
        		</li>
        		<li class="flx fwd spb htg rr">
        			<span class="rcx2"></span>
        			<span class="rcx4">Wallet version: </span>
        			<strong class="rcx6">{status.walletver.podjsonrpcapi.versionstring}</strong>
        		</li>
        		<li class="flx fwd spb htg rr">
        			<span class="rcx2"></span>
        			<span class="rcx4">Uptime: </span>
        			<strong class="rcx6">{status.uptime}</strong>
        		</li>
        		<li class="flx fwd spb htg rr">
        			<span class="rcx2"></span>
        			<span class="rcx4">Memory: </span>
        			<strong class="rcx6">{status.net}</strong>
        		</li>

        		<li class="flx fwd spb htg rr">
                			<span class="rcx2"></span>
                			<span class="rcx4">Disk: </span>
                			<strong class="rcx6">{status.ver}</strong>
                		</li>
                		<li class="flx fwd spb htg rr">
                			<span class="rcx2"></span>
                			<span class="rcx4">Chain: </span>
                			<strong class="rcx6">{status.walletver.podjsonrpcapi.versionstring}</strong>
                		</li>
                		<li class="flx fwd spb htg rr">
                			<span class="rcx2"></span>
                			<span class="rcx4">Blocks: </span>
                			<strong class="rcx6">{status.uptime}</strong>
                		</li>
                		<li class="flx fwd spb htg rr">
                			<span class="rcx2"></span>
                			<span class="rcx4">Connections: </span>
                			<strong class="rcx6">{status.net}</strong>
                		</li>
	</ul>
</div>

// pkg/gui/vue/src/panels/PanelStatus.vue
<script>
export default{

    }
</script>
<template>
<div class="rwrap">
    <ul class="rf flx flc noPadding justifyEvenly">
        <li class="flx fwd spb htg rr">
            <span class="rcx2"></span>
            <span class="rcx4">Version: </span>
            <strong class="rcx6"><span v-html="this.status.ver"></span></strong>
        </li>
		<li class="flx fwd spb htg rr">
            <span class="rcx2"></span>
            <span class="rcx4">Wallet version: </span><strong class="rcx6">
            <span v-html="this.status.walletver.podjsonrpcapi.versionstring"></span></strong>
        </li>

        <li class="flx fwd spb htg rr">
            <span class="rcx2"></span>
            <span class="rcx4">Uptime: </span>
            <strong class="rcx6">
            <span v-html="this.status.uptime"></span></strong>
        </li>

		<li class="flx fwd spb htg rr">
            <span class="rcx2"></span>
            <span class="rcx4">Memory: </span>
            <strong class="rcx6">
            <span v-html="this.status.mem.total"></span></strong>
        </li>
		<li class="flx fwd spb htg rr">
            <span class="rcx2"></span>
            <span class="rcx4">Disk: </span>
            <strong class="rcx6">
            <span v-html="this.status.disk.total"></span></strong>
        </li>

		<li class="flx fwd spb htg rr">
            <span class="rcx2"></span>
            <span class="rcx4">Chain: </span>
            <strong class="rcx6">
            <span v-html="this.status.net"></span></strong>
        </li>
		<li class="flx fwd spb htg rr">
            <span class="rcx2"></span>
            <span class="rcx4">Blocks: </span>
            <strong class="rcx6">
            <span v-html="this.status.blockcount"></span></strong>
        </li>
        <li class="flx fwd spb htg rr">
            <span class="rcx2"></span>
            <span class="rcx4">Connections: </span>
            <strong class="rcx6">
            <span v-html="this.status.connectioncount"></span></strong>
        </li>
    </ul>
</div>
</template>

<script>
export default {
	name: 'PanelBalance',
	props:{
		status:Object,
	}
}
</script>
